### ISSUE TITLE
Issue with compilation on Debian Stretch (QT 5.7)

### ISSUE THREAD

**Issue by jdeplaa** [schirmermischa/THELI#2]
Hi Mischa,

For the group of Peter Jonker, I am attempting to compile Theli v3 on our Debian Stretch systems at SRON. Unfortunately, I am running into a QT version issue. In the memoryviewer.cc program, you use a .isEmpty() method, which is not available in QT 5.7, which happens to be the default on Debian Stretch. See the error below:

```
g++ -c -m64 -pipe -fopenmp -g -Wno-unused -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/data/jellep/HEA/THELI/src"' -I. -isystem /usr/include/wcslib -isystem /usr/local/include/wcslib/ -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtTest -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o memoryviewer.o dockwidgets/memoryviewer.cc
dockwidgets/memoryviewer.cc: In member function ‘void MemoryViewer::addBackupDirs(const QString&)’:
dockwidgets/memoryviewer.cc:297:25: error: ‘class QDir’ has no member named ‘isEmpty’
                 && !dir.isEmpty()) {
                         ^~~~~~~
Makefile:2353: recipe for target 'memoryviewer.o' failed
```

At home, I have a more recent Debian version with QT 5.11 and there the code compiles fine. I see that you use QT 5.9. 

I guess this issue will resolve itself over time when people upgrade to newer Linux distros, but if it is easy, pushing the QT compatibility down to version 5.7 would be appreciated. I can help with testing that if you want.

Thanks and cheers.

**Comment by schirmermischa** [comment]
Hi, I replaced the functions accordingly. Please let me know whether it now compiles with Qt 5.7. If not, then I'm not sure I want to go down a potentially bottomless rabbit hole. Please fetch the master branch for testing!

best, mischa

**Comment by jdeplaa** [comment]
Thanks a lot for replacing these functions! I have tested the latest commit and managed to compile theli on debian stretch, however, with a few small modifications of the code to fix a couple of compilation errors (which you should definitively review carefully before including my changes). I did it this way to see for you how deep the 'rabbit hole' is. Fortunately, it appears to be limited to a few (minor) issues.

I list below the result of a ``git diff`` on the src directory that compiled successfully and comment them:

**ISSUE 1:** At line 109 of status.cc, the compiler gave the following error:
```
status.cc:109:32: error: no match for ‘operator!=’ (operand types are ‘const QChar’ and ‘const char [2]’)
         if (statusString.at(i) != " ") lastId = i;
```
So it appears that it doesn't like the fact that the result of ``statusString.at(i)`` is not a ``char`` type. Perhaps this could be solved by using a method to see if the string is empty (or Null?). The following change compiled, but it should be verified whether this gives the desired behaviour.
```
--- a/src/status.cc
+++ b/src/status.cc
@@ -106,7 +106,7 @@ int Status::lastExecutedTaskId()
         return 0;
     }
     for (int i=0; i<numtasks; ++i) {
-        if (statusString.at(i) != " ") lastId = i;
+        if ( ! statusString.at(i).isNull() ) lastId = i;
     }
     return lastId;
 }
```

**ISSUE 2:**
In the file debayer.cc the compiler complained about using a double in the abs() function (in multiple locations in the file):
```
tools/debayer.cc: In function ‘void debayer(int, MyImage*, MyImage*, MyImage*, MyImage*)’:
tools/debayer.cc:241:91: error: call of overloaded ‘abs(float)’ is ambiguous
                 float DN = abs(image->dataCurrent[(i-2*n+n*j)]-image->dataCurrent[(i+n*j)])*2.0
```
In this file, it was solved by simply adding ``<cmath>`` to the includes. Hopefully this does not have any unintended effects.
```
--- a/src/tools/debayer.cc
+++ b/src/tools/debayer.cc
@@ -20,6 +20,7 @@ If not, see https://www.gnu.org/licenses/ .
 #include "tools.h"
 #include "../myimage/myimage.h"
 #include <QDebug>
+#include <cmath>
```

**ISSUE 3:**
In tools/detectedobject.cc, there was a very similar issue as the previous one. Also related to the use of ``abs()``.
```
tools/detectedobject.cc: In member function ‘void DetectedObject::calcWindowedMomentsErrors()’:
tools/detectedobject.cc:484:52: error: call of overloaded ‘abs(double)’ is ambiguous
         ERRTHETAWIN = abs(0.5*atan(ERRTHETAWIN)/rad);
```
This issue appears to be solved by using ``fabs()`` instead of ``abs()``. As far as I can see, these functions should provide the desired result. Hopefully a test can verify that.
```
--- a/src/tools/detectedobject.cc
+++ b/src/tools/detectedobject.cc
@@ -438,7 +438,7 @@ void DetectedObject::calcMomentsErrors()
     ERRB = sqrt(ERRB);
 
     ERRTHETA = 2.*ERRXY / (ERRX2-ERRY2);
-    ERRTHETA = abs(0.5*atan(ERRTHETA)/rad);
+    ERRTHETA = fabs(0.5*atan(ERRTHETA)/rad);
 
     // noise floor
     if (ERRTHETA < 0.01) ERRTHETA = 0.01;
@@ -481,7 +481,7 @@ void DetectedObject::calcWindowedMomentsErrors()
         ERRAWIN = sqrt(ERRAWIN);
         ERRBWIN = sqrt(ERRBWIN);
         ERRTHETAWIN = 2.*ERRXYWIN / (ERRX2WIN-ERRY2WIN);
-        ERRTHETAWIN = abs(0.5*atan(ERRTHETAWIN)/rad);
+        ERRTHETAWIN = fabs(0.5*atan(ERRTHETAWIN)/rad);
     }
     else {
         ERRX2WIN = 0.;
```

After making the changes above, theli compiled succesfully and could be started on debian with QT 5.7. It would be greatly appreciated if you can look at the issues above. Thanks and cheers!

**Comment by schirmermischa** [comment]
Dear Jelle,

thanks a lot for spotting the issue with the incorrect use of abs(). I'm using fabs() everywhere else in the code, and fixed it accordingly. Your first issue about the QChar / char comparison, it was used in a function that was not used anywhere else in the code, so I simply commented it out. Changes are reflected already in the master branch.
